@echo off
setlocal

set TOOLS=../Tools

set PATH=%TOOLS%\tasm32;%TOOLS%\zxcc;%TOOLS%\intel;%PATH%

set TASMTABS=%TOOLS%\tasm32

set CPMDIR80=%TOOLS%/cpm/


DEL *.REL
DEL *.PRN
DEL BNKXIOS.SPR
ZXCC ZSM XIOS,XIOS=XIOS.Z80
ZXCC LINK BNKXIOS=XIOS[NR,OS]
COPY /y BNKXIOS.SPR ..\Kernel
PAUSE
